services:
  db:
    container_name: agat_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: agat_db
      POSTGRES_USER: agat_manager
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: agat_backend
    build:
      context: .
      dockerfile: ./backend/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data: