import os

BACKEND_SERVER_PORT = os.getenv("BACKEND_SERVER_PORT", 8000)
POSTGRES_PORT = os.getenv("PGPORT", 5432)
POSTGRES_DB = os.getenv("POSTGRES_DB", "AGAT")
POSTGRES_USER = os.getenv("POSTGRES_USER", "e_commerce_manager")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", 123)
API_KEY=os.getenv("API_KEY")


# General
APP_NAME = "AGAT"


SQL_ALCHEMY_DB_CONNECTION_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db:{POSTGRES_PORT}/{POSTGRES_DB}"
